import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useSession, getSession } from "next-auth/react";
import { signOut } from "next-auth/react";
import Table from '../components/table'
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session } = useSession();
  const  handleLogout= () => {
    signOut();
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {session?User({session}): Guest()}
        <Table></Table>
      </main>
    </>
  );

  function Guest() {
    return (
      <h1>Guest</h1>
    );
  }
  
  function User({session}) {
    return (
      <>
      <h1>Name: {session.user.name}</h1>
      <h1>Email: {session.user.email}</h1>
      <button onClick={handleLogout}>Logout</button>
      </>
    )
  }
}

// proetected route
//https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props
export async function getServerSideProps ({req, res, next}){
  const session = await getSession({req});
  if (!session) {
    return{
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }
  return {
    props: {session}
  }
}